apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tunnel: cf-tunnel
  name: cf-tunnel
  namespace: default
spec:
  replicas: 3 # you might want to adjust the replicas to your own needs
  selector:
    matchLabels:
      tunnel: cf-tunnel
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tunnel: cf-tunnel
    spec:
      containers:
        image: cloudflare/cloudflared:latest # you might want to pin this to a version
        command: ["/bin/sh"]
        args:
          [
            "-c",
            'echo "Token: $CF_TUNNEL_TOKEN"; tunnel --no-autoupdate run --token "$CF_TUNNEL_TOKEN"',
          ]
        env:
          - name: CF_TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: cf-tunnel
                key: token
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: tunnel
        ports:
          - containerPort: 8081
            name: http-metrics
