---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: fluxcd-glucktek
  url: https://github.com/Glucktek/testing

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: test-app
  targetNamespace: default
  timeout: 3m0s
  wait: true
